// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz-PHqOm8BA3WCf77je9YgmNNl2sXWiOs',
    appId: '1:591302786053:web:fd1a1e296d44a6e1efb06c',
    messagingSenderId: '591302786053',
    projectId: 'snowlive-cf446',
    authDomain: 'snowlive-cf446.firebaseapp.com',
    storageBucket: 'snowlive-cf446.appspot.com',
    measurementId: 'G-ZNTCBJMNZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn5b_h-FOnbikjhthJaHmY_YxCWBPdxyQ',
    appId: '1:591302786053:android:7fbcee13bb3c99fcefb06c',
    messagingSenderId: '591302786053',
    projectId: 'snowlive-cf446',
    storageBucket: 'snowlive-cf446.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDud4jDe4AZUL9wO-RibFJ47JM-gixPB5o',
    appId: '1:591302786053:ios:1ff67b60fddd69f7efb06c',
    messagingSenderId: '591302786053',
    projectId: 'snowlive-cf446',
    storageBucket: 'snowlive-cf446.appspot.com',
    androidClientId: '591302786053-1ei8td6j12ea8t3n12m2gkgvcmngtna8.apps.googleusercontent.com',
    iosClientId: '591302786053-c7ne6ak4v1ettfqqtnsjsf8rehntkdsp.apps.googleusercontent.com',
    iosBundleId: 'com.snowlive',
  );
}
